### ISSUE TITLE
Navigation: Table/Record page action to access activities page

### ISSUE THREAD

**Issue by nikspyratos** [pxlrbt/filament-activity-log#15]
👋 Heyo. Neat package!

I've followed the installation instructions and I've noticed there is no direct way to navigate to a given user/model's activities other than directly going to `/{record}/activities`. Am I missing something, or would it be good to have actions to access activities from the List and View pages?

I can have a crack at it over the weekend, but wanted to highlight it for now.

**Comment by pxlrbt** [comment]
Not sure why you need an Action for that? It's basically

```php
Action::make('activities')->url(YourResource::getUrl('activities'))
```

**Comment by nikspyratos** [comment]
Yeah, that's basically what I was going to do. Probably didn't word my issue correctly - I'm saying that this should probably be included or have a quick instruction to add.

**Comment by pxlrbt** [comment]
Not sure whether you have access to the resource from within an action? So it's probably not possible to build this upfront. I'll add it to the docs, to make it easier for people, even if it should be clear from Filament docs.
