### ISSUE TITLE
Action isn't being passed the record object

### ISSUE THREAD

**Issue by kirkbushell** [pxlrbt/filament-activity-log#16]
After following the steps, seeing this error when listing users:

Missing required parameter for [Route: filament.admin.resources.users.activities] [URI: admin/users/{record}/activities] [Missing parameter: record].

**Comment by kirkbushell** [comment]
The docs need to be updated to reflect the v3 version of using url - it should be passed a callback, then pass the record into the getUrl paramters.

**Comment by albertobenavides** [comment]
Im doing this: 
```php
Action::make('activities')
                    ->url(fn (ModelName $record): string => ModelNameResource::getUrl() . "/$record->id/activities")
```

**Comment by kirkbushell** [comment]
> Im doing this:
> 
> ```
> Action::make('activities')
>                     ->url(fn (ModelName $record): string => ModelNameResource::getUrl() . "/$record->id/activities")
> ```

Yup, exactly - as I said, it needs to be passed a callback, not just the record object, as per the documentation ;)
