### ISSUE TITLE
Restore doesn't do anything

### ISSUE THREAD

**Issue by kirkbushell** [pxlrbt/filament-activity-log#17]
There are no requests being made to the server, and so no reversion is actually done when clicking the button. 

Have tested this numerous times across a bunch of resources.

**Comment by albertobenavides** [comment]
I have used this function just now. Have you added this into the model?
```php
use LogsActivity;

public function getActivitylogOptions(): LogOptions
{
    return LogOptions::defaults()
        ->logOnly(['*']);
}
```

**Comment by kirkbushell** [comment]
I have.

**Comment by albertobenavides** [comment]
Oh, yeah, hahaha. Just an example. You should only log non sensible data :)

**Comment by pxlrbt** [comment]
Since it's working for some people, could you provide a reproduction repo so I can have a look at it?
