### ISSUE TITLE
Typed property pxlrbt\FilamentActivityLog\Pages\ListActivities::$record must not be accessed before initialization

### ISSUE THREAD

**Issue by flashmediasolutions** [pxlrbt/filament-activity-log#23]
Having an issue on fresh install.

Not sure if this is related to this statement, that I am unsure how to execute:
> Make sure you use a custom theme and the vendor folder for this plugins is published, so that it includes the Tailwind CSS classes.

If I go into the cache file and remove `@livewire('livewire-ui-spotlight')` it loads the page.

Any help would be greatly appreciated!

![Screenshot 2023-10-04 at 2 44 38 PM](https://github.com/pxlrbt/filament-activity-log/assets/12239388/7ff1e6cb-d9f6-40ef-99f6-35b219abd332)

**Comment by flashmediasolutions** [comment]
It looks like it's a conflict with your other plugin [https://filamentphp.com/plugins/pxlrbt-spotlight](url)

**Comment by pxlrbt** [comment]
Yeah looks like. Does it break immediately or only when you visit that page?

**Comment by flashmediasolutions** [comment]
It breaks immediately. I don't have Flare. What would you need from Telescope?

**Comment by pxlrbt** [comment]
You just sent a screenshot of it 😅 Just click "Share" in the top right to create a shareable link.

**Comment by Saifallak** [comment]
same error when using something like this:

```php
   Forms\Components\Section::make(__('Address Information'))
                            ->relationship('address')
                            ->collapsible()
                            ->columnSpan(3)
                            ->schema(fn(Forms\Get $get) => self::addressForm(defaultName: ($get('name') ?? 'Shop') . ' Name')),
```

**Comment by DevRaeph** [comment]
Same problem here :D
Here's my Flare share: https://flareapp.io/share/xmNw6L8P

**Comment by DevRaeph** [comment]
@pxlrbt i can confirm this PR fixed the issue.
