### ISSUE TITLE
Class "Js" not found with version 1.0.2

### ISSUE THREAD

**Issue by adriaardila** [pxlrbt/filament-activity-log#25]
Hello,

After updating to the last version I'm getting this error. Version 1.0.1 works fine.

![image](https://github.com/pxlrbt/filament-activity-log/assets/2029010/28251a6f-df3c-4ceb-9ede-269aedb72dc7)

**Comment by pxlrbt** [comment]
Should be fixed by #26 and in version v1.0.3

**Comment by adriaardila** [comment]
All good and working now, thank you!
