### ISSUE TITLE
Call to undefined method App\Models\User::activities()

### ISSUE THREAD

**Issue by wiwa1978** [pxlrbt/filament-activity-log#31]
I always get this error message. I have created the ListUserActivities under Filament\Resource\UserResource\Pages. In the UserResource I registered the page and added an action to the table. I see the Activities link next to each user but when I click on it, I always get the `Call to undefined method App\Models\User::activities()` error.

**Comment by bo3bdo** [comment]
Me too

**Comment by pxlrbt** [comment]
You too what? 😅

**Comment by bo3bdo** [comment]
Oh, sorry the database was empty

I installed the package and seeded the base and all good now thank you

**Comment by pxlrbt** [comment]
Since there is no reaction from @wiwa1978, and I don't think this is an issue, I'll close this now.
